@TaskManagementApi_HostAddress = http://localhost:5000

### Get all tasks
GET {{TaskManagementApi_HostAddress}}/tasks/
Accept: application/json

### Get by Id

GET {{TaskManagementApi_HostAddress}}/tasks/52999b71-3cd9-47ed-892f-d6797c2f1438
Accept: application/json

### Add new Task

POST {{TaskManagementApi_HostAddress}}/tasks/
Accept: application/json
Content-Type: application/json

{
  "id": "{{$uuid}}",
  "title": "Task Title",
  "content": "content"
}

### Toogle task completion

PATCH {{TaskManagementApi_HostAddress}}/tasks/7dedb1b5-e158-47f6-8a60-a0dd613169e9
Accept: application/json
Content-Type: application/json

true
